"use client"
import Navbar from "../../components/Navbar";
import backgroundImage from '../../public/bgimg1.jpg';
import "./globals.css";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <div style={{
            backgroundImage: `url(${backgroundImage.src})`,
            width : "100vw",
            height : "100vh"
          }} >
            <Navbar />
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}